defmodule Helpdesk.Repo.Migrations.AddJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:programming_languages, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
    end

    create unique_index(:programming_languages, ["name"],
             name: "programming_languages_name_index"
           )

    create table(:jobs, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :title, :text, null: false
      add :state, :text, null: false, default: "new"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:job_programming_languages, primary_key: false) do
      add :job_id,
          references(:jobs,
            column: :id,
            name: "job_programming_languages_job_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :programming_language_id,
          references(:programming_languages,
            column: :id,
            name: "job_programming_languages_programming_language_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:job_programming_languages, "job_programming_languages_job_id_fkey")

    drop constraint(
           :job_programming_languages,
           "job_programming_languages_programming_language_id_fkey"
         )

    drop table(:job_programming_languages)

    drop table(:jobs)

    drop_if_exists unique_index(:programming_languages, ["name"],
                     name: "programming_languages_name_index"
                   )

    drop table(:programming_languages)
  end
end
